### ISSUE TITLE
chrome driver error on first run

### ISSUE THREAD

**Issue by sprugman** [mojotech/pioneer#262]
scaffolding worked, but then

```
$ ./node_modules/.bin/pioneer
```

lead to

<pre>
Configuration loaded from /Users/Micah/Sites/kydaepi/admin/pioneer.json

Feature: Simple Feature   # tests/features/simple.feature

  Scenario: Entering Information

/Users/Micah/Sites/kydaepi/admin/node_modules/pioneer/node_modules/selenium-webdriver/lib/webdriver/promise.js:1643
      throw error;
            ^
Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
    at Error (<anonymous>)
    at new ServiceBuilder (/Users/Micah/Sites/kydaepi/admin/node_modules/pioneer/node_modules/selenium-webdriver/chrome.js:51:11)
    at getDefaultService (/Users/Micah/Sites/kydaepi/admin/node_modules/pioneer/node_modules/selenium-webdriver/chrome.js:216:22)
    at Object.createDriver (/Users/Micah/Sites/kydaepi/admin/node_modules/pioneer/node_modules/selenium-webdriver/chrome.js:450:32)
    at createNativeDriver (/Users/Micah/Sites/kydaepi/admin/node_modules/pioneer/node_modules/sele
</pre>

**Comment by sdvig** [comment]
I've also got this error:
```
Error: The ChromeDriver could not be found on the current PATH.
```
Not sure that's the right solution -- but to make it work I have to [download the chrome driver](http://chromedriver.storage.googleapis.com/index.html) & copy it to /usr/bin.
