### ISSUE TITLE
integration tests are failing when using chrome driver

### ISSUE THREAD

**Issue by shoe** [mojotech/pioneer#322]
$ npm run integration
...
```
Failing Scenarios: 
/home/chris/git/pioneer/test/integration/features/shorthand.feature:7
UnknownError: unknown error: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
  (Session info: chrome=42.0.2311.135)
  (Driver info: chromedriver=2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.19.3-100.fc20.x86_64 x86_64)
    at new bot.Error (/home/chris/git/pioneer/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/chris/git/pioneer/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)

/home/chris/git/pioneer/test/integration/features/simple.feature:14
AssertionError: expected 'https://www.google.com/?gws_rd=ssl' to deeply equal 'http://www.google.com/'
From: Task: <anonymous>
    at /home/chris/git/pioneer/lib/support/index.js:9:3777
    at /home/chris/git/pioneer/node_modules/selenium-webdriver/lib/webdriver/promise.js:2546:12
    at promise.ControlFlow.runInFrame_ (/home/chris/git/pioneer/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
```

**Comment by samccone** [comment]
Fixed in
ae012636a61129f0b78018869419edfe11ba6a84
44ceb2b9a4b3c3257831a1186fc19a367f9c07b2

**Comment by shoe** [comment]
:+1: confirmed. all green in chrome.
