### ISSUE TITLE
Unable to install with npm@3

### ISSUE THREAD

**Issue by hhsnopek** [mojotech/pioneer#329]
npm@3 gives the worst error messages, it's no error message. But just making this for a note that it'll break when 3.0 goes live

**Comment by samccone** [comment]
mind listing the error ha :)

**Comment by hhsnopek** [comment]
![npm 3 error](https://cldup.com/auaetehUmw.png)

**Comment by samccone** [comment]
We might want to file this over in npm land since 3 is still in beta

cc @linclark

**Comment by hhsnopek** [comment]
I think it has to do with peerDependencies breaking change - https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by linclark** [comment]
Testing this out, I don't even get any progress on the installation progress bar even after letting it hang for a while. So there's definitely some issue there. I'll see if I can find an answer for this.

**Comment by samccone** [comment]
thanks a bunch @linclark !

**Comment by hhsnopek** [comment]
I just cloned this locally and attempted to `install` and `link` pioneer. There appears to be an issue when installing `bufferutil@1.0.1` from `utf-8-validate@1.0.1`. I then switched from iojs v2.2.1 to node v0.12.5 and was successfully able to install pioneer with all it's dependencies. Switching back to iojs v2.2.1 with pioneer installed with node v0.12.5 I am still able to use pioneer. Which means that this issue is caused from when using iojs to install and not from npm. 

```
ϟ pioneer (master) ✔  npm link

> utf-8-validate@1.0.1 install /Users/henrysnopek/projects/pioneer/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../../nan/nan.h:74:
In file included from ../../nan/nan_new.h:190:
../../nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function
      call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/henrysnopek/.node-gyp/2.2.1/deps/v8/include/v8.h:4188:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/henrysnopek/projects/pioneer/node_modules/utf-8-validate
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN install:utf-8-validate Couldn't install optional dependency: utf-8-validate@1.0.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1

> bufferutil@1.0.1 install /Users/henrysnopek/projects/pioneer/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:74:
In file included from ../../nan/nan_new.h:190:
../../nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function
      call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/henrysnopek/.node-gyp/2.2.1/deps/v8/include/v8.h:4188:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/henrysnopek/projects/pioneer/node_modules/bufferutil
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN install:bufferutil Couldn't install optional dependency: bufferutil@1.0.1 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1
pioneer@0.11.4 /Users/henrysnopek/projects/pioneer
└── gulp-include@0.2.3  (git://github.com/samccone/gulp-include.git#59e9a1dd4068412a6d35a49b8ef586a3063b92d3)

/usr/local/bin/pioneer -> /usr/local/lib/node_modules/pioneer/bin/pioneer
/usr/local/lib/node_modules/pioneer -> /Users/henrysnopek/projects/pioneer
```

**Comment by hhsnopek** [comment]
[npm-shrinkwrap.json#L421](https://github.com/mojotech/pioneer/blob/master/npm-shrinkwrap.json#L421) - link to bufferutil from npm-shrinkwrap.json

**Comment by iarna** [comment]
That original error was specifically a bug that caused _node.js_ to crash with `3.0.0`. We can't print out an error message when we've set `node.js` on fire. =p Obviously we don't want to do that. =D (`npm@3.1.0` stops it from setting fire to things).

**Comment by samccone** [comment]
:fire: :fire_engine: :droplet: 

thanks so much @iarna and @linclark and @hhsnopek :clap:

**Comment by iarna** [comment]
And yeah, the optional deps fail there, because they haven't been updated to support io.js yet, looks like. Fortunately they're optional! =)

**Comment by hhsnopek** [comment]
Yay! it works, just installed with npm 3.1.0 & io.js 2.2.1
Thank you @iarna and @linclark :smile:
